# Generated by Django 2.2.7 on 2019-12-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='newtest.UserModel')),
            ],
        ),
    ]
